data:
  processed: True # If processed=True, load inference data from processed_inference_data_path. Otherwise, will process the data from raw_inference_data_dir (refer to /bionemo/data/dsmbind/preprocess.py for the required structure of the raw data directory).
  raw_inference_data_dir: ${oc.env:BIONEMO_HOME}/examples/tests/test_data/molecule/dsmbind/inference # directory to raw inference data
  processed_inference_data_path: /dsm/data/drug/test_casf16.pkl # path to processed inference data

model:
  hidden_size: 256 # number of hidden dimensions
  mpn_depth: 3 # depth of the message passing network
  num_heads: 4 # number of attention heads in the Transformer encoder layer
  dropout: 0.1 # dropout rate
  threshold: 10.0 # distance cutoff threshold
  vocab_size: 38 # number of atom types, vocab_size=len(ATOM_TYPES)
  aa_size: 21 # number of residue types, aa_size=len(ALPHABET)
  max_residue_atoms: 14 # max number of residue atoms

inference:
  num_gpus: 1  # number of GPUs
  ckpt_path: ${oc.env:BIONEMO_HOME}/models/molecule/dsmbind/dsmbind.pth # path to the trained checkpoint
